on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: https://raw.githubusercontent.com/wetransform-os/ProMCDA/main/JOSS_paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: https://raw.githubusercontent.com/wetransform-os/ProMCDA/main/JOSS_paper/paper.pdf